language: php

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: LARAVEL='5.8.*' COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.2
          env: LARAVEL='5.8.*'
        - php: 7.2
          env: LARAVEL='6.*' COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.2
          env: LARAVEL='6.*'
        - php: 7.2
          env: LARAVEL='7.*' COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.2
          env: LARAVEL='7.*'
        - php: 7.3
          env: LARAVEL='5.8.*' COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.3
          env: LARAVEL='5.8.*'
        - php: 7.3
          env: LARAVEL='6.*' COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.3
          env: LARAVEL='6.*'
        - php: 7.3
          env: LARAVEL='7.*' COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.3
          env: LARAVEL='7.*'

before_install:
    - travis_retry composer self-update
    - travis_retry composer require --no-update --no-interaction "laravel/framework:${LARAVEL}"

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit
